home work Page 1.0
MarinaFedkova/Android_nmedia pull request #6
Opened 2021-07-13 18:20 UTC by MarinaFedkova

2021-07-14 17:49 UTC, maks1596 requested changes
Поменьше закомментированного кода, который Вам уже никогда не пригодится

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/adapter/PostsAdapter.kt
> +        }
Исправляйте в домашней работе 😊

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/application/NMediaApplication.kt
> +        //setupWork()
Удалите, пожалуйста. С помощью гита вы всё спокойно восстановите. Тем более этот закомментированный код не обладает какой-то сложностью и от того не очень ценен

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostPagingSource.kt
> +                )
У Вас есть метод `getAfter(...)` - используйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostPagingSource.kt
> +    private val servise: ApiService,
Опечатка
```suggestion
    private val serviсe: ApiService,
```

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
> +    }*/
Не комментируйте - удаляйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
> +            //repository.stream.cachedIn(viewModelScope)
Не комментируйте - удаляйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
> +            //repository.readAll()
Не комментируйте - удаляйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
>      fun likeById(id: Long) {
Метод больше ничего не делает? Тогда удаляйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/viewmodel/PostViewModel.kt
>      fun removeById(id: Long) {
Метод больше ничего не делает? Тогда удаляйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/ui/FragmentFeed.kt
> +        }*/
Не комментируйте - удаляйте

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/ui/FragmentFeed.kt
> +@ExperimentalCoroutinesApi
Лучше не надо использовать эту аннотацию:
1. Непонятно к чему она на самом деле написана, когда прописана на уровне класса.
2. Когда библиотека с корутинами обновится, то API перестанет быть эксперементальным, а Ваш фрагмент - нет.

2021-07-14 17:49 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/ui/FragmentFeed.kt
>  class FragmentFeed : Fragment() {
Обычно название родительского класса приписывается в конце названия дочернего.
```suggestion
class FeedFragment : Fragment() {
```

2021-07-15 09:05 UTC, MarinaFedkova commented on app/src/main/java/ru/netology/nmedia/repository/PostPagingSource.kt
> +    private val servise: ApiService,
Спасибо! Сама вряд ли бы заметила.

2021-07-15 09:09 UTC, MarinaFedkova commented on app/src/main/java/ru/netology/nmedia/ui/FragmentFeed.kt
> +@ExperimentalCoroutinesApi
Тут я последовала совету Студии, и прописала аннотацию без четкого понимания, что делаю.
Интересно, а если аннотацию оставить, то когда библиотека обновится, Студия посоветует убрать аннотацию или нет?

2021-07-15 09:11 UTC, MarinaFedkova commented on app/src/main/java/ru/netology/nmedia/ui/FragmentFeed.kt
>  class FragmentFeed : Fragment() {
О, правила образования названий фрагментов не понимала, спасибо!

2021-07-18 00:42 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/ui/FragmentFeed.kt
> +@ExperimentalCoroutinesApi
Едва ли 😊 Поэтому лучше не проставлять эту аннотацию в своём коде

2021-07-18 01:07 UTC, maks1596 approved these changes

2021-07-18 01:07 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryImpl.kt
> +    private val pageSize = 10
1. `pageSize` - константа. 
   1. Для константы в котлине есть ключевое слово `const`. 
   2. Константы традиционно именуются в `CAPS_CASE`.
   3. Если коротко, то:  
   ```suggestion
       private companion object {
           private const val PAGE_SIZE = 10
       }
   ```
2. `pageSize` используется только в одном месте:
   1. Вы уверены, что Вам нужно тогда отдельно выделять эту константу?
   2. Может есть смысл использовать её же в `PagingConfig`?

2021-07-18 01:07 UTC, maks1596 commented on app/src/main/java/ru/netology/nmedia/ui/FeedFragment.kt
> +
А зачем Вы эти `Inject`-ы добавили? Судя по поиску по фрагменту они нигде не используются 🤔

2021-07-20 10:28 UTC, MarinaFedkova commented on app/src/main/java/ru/netology/nmedia/repository/PostRepositoryImpl.kt
> +    private val pageSize = 10
Максим, большое спасибо за подробную обратную связь!

2021-07-20 10:36 UTC, merged